[project]
name = "ingest"
version = "0.1.0"
description = "Example data ingestion with dlt"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt[duckdb]",
    "pyarrow",
    "sqlalchemy",
]
