[project]
name = "transform"
version = "0.1.0"
description = "Example dbt data transformation project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core",
    "dbt-duckdb",
]
