[project]
name = "transform"
version = "0.1.0"
description = "Example dbt data transformation project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core==1.8.8",
    "dbt-duckdb==1.8.4",
]
