[project]
name = "app-tests"
version = "0.1.0"
description = "API tests for example web app"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography",
    "httpx",
    "pytest-asyncio",
    "pytest",
    "python-dotenv",
]
